### ISSUE TITLE
Documented response string for `getStatus().description` is incorrect

### ISSUE THREAD

**Issue by maschad96** [ffflorian/api-clients#1241]
https://github.com/ffflorian/api-clients/blob/4e91faf893c647dd17766ffc64d48b9060b9c0c1/packages/statuspage.io/src/Statuspage.ts#L53

`Partial System Outage` should be `Partially Degraded Service`

Uncertain about the accuracy of 'major service outage', will check.

**Comment by ffflorian** [comment]
Hi @maschad96, where did you find the string `Partially Degraded Service`?

**Comment by ffflorian** [comment]
Ah, I see - seems like the official documentation is wrong (that's where I got the original string from).
