### ISSUE TITLE
Issue with Axion client - API V1 call returns status 404 (statuspage.io)

### ISSUE THREAD

**Issue by isak-dombestein** [ffflorian/api-clients#588]
The Axion client used in this client is fine, but it needs to have a change made to it.

In /statuspage.io/src/Endpoints.js it has an API call to the Statuspage API V1. This has now been removed and API V2 is the only one working. All V1 calls returns a 404 error. I went into the Endpoints file and ended up changing 
`const API_V1_BASE = 'api/v1'` to `const API_V2_BASE = 'api/v2'` and replace all API_V1_BASE calls in this document to the new API_V2_BASE.

**Comment by ffflorian** [comment]
Hi @isak-dombestein, thanks for the info! I'll fix it in the next days.

**Comment by ffflorian** [comment]
@isak-dombestein is it working for you with v3.0.3?

**Comment by isak-dombestein** [comment]
Hi,

Yes, Version 3.0.3 has this issue fixed for me now.
