### ISSUE TITLE
Method getCrates() can't search package correctly

### ISSUE THREAD

**Issue by Kayxue** [ffflorian/api-clients#653]
Code:
![image](https://user-images.githubusercontent.com/26020165/115677213-d801ba80-a382-11eb-9ba5-3f0323a903e5.png)
Output:
![image](https://user-images.githubusercontent.com/26020165/115677292-ec45b780-a382-11eb-8ec8-dd1fdc2f9a4f.png)

I fixed this problem by modified here:
![image](https://user-images.githubusercontent.com/26020165/115677618-3d55ab80-a383-11eb-9263-ff5f0480775f.png)

I hope you can fix the problem of this package

**Comment by ffflorian** [comment]
Thanks @Kayxue, will fix it ASAP.

**Comment by ffflorian** [comment]
Fixed with version 2.0.6.
