### ISSUE TITLE
Unable to search npms.io using specific keywords and operators

### ISSUE THREAD

**Issue by pdehaan** [ffflorian/api-clients#948]
I'm trying to use the https://www.npmjs.com/package/npms.io client to search npms.io by a specific keyword and non-deprecated plugins: `keywords:eleventy-plugin not:deprecated`

If I was using the API directly, I'd use something like this: 
https://api.npms.io/v2/search?q=keywords:eleventy-plugin+not:deprecated

I'm not sure how to do that w/ the NpmsIO client though. I tried this:

```js
import { NpmsIO } from "npms.io";

const npmClient = new NpmsIO();

const plugins = await npmClient.api.search.searchPackage("keywords:eleventy-plugin not:deprecated", {size:250});
console.log(plugins);
```

&hellip; but it always returns zero results: `{ total: 0, results: [] }`

If I remove the `encodeURIComponent()` from this line and just do `q: query` in my local ./node_modules/ folder, then I start seeing results:
https://github.com/ffflorian/api-clients/blob/72b216144d7d579d77150c6342364a0989ef1b6f/packages/npms.io/src/api/SearchAPI.ts#L58

```diff
- q: encodeURIComponent(query)
+ q: query
```

```js
{
  total: 154,
  results: [
    { package: [Object], score: [Object], searchScore: 0.0007207585 },
    { package: [Object], score: [Object], searchScore: 0.00066178717 },
    ...
  ]
}
```

**Comment by pdehaan** [comment]
Also filed upstream at https://github.com/npms-io/npms/issues/53 in case it is an npms.io issue. :shrug:

**Comment by pdehaan** [comment]
Upstream issue was my fault, it was encoding the `+` as %2B instead of me using spaces and it encoding as %20.

So the API supports encoded values: https://api.npms.io/v2/search?from=0&q=keywords%3Aeleventy-plugin%20not%3Adeprecated%20scope%3A11ty&size=250

Not sure why I can't get it working through the API:

```js
import { NpmsIO } from "npms.io";

const npmClient = new NpmsIO();

const plugins = await npmClient.api.search.searchPackage("keywords:eleventy-plugin not:deprecated", {size:250});
console.log(plugins); // { total: 0, results: [] }
```

### OUTPUT

```js
// node_modules/npms.io/dist/api/SearchAPI.js
console.log({endpoint, params});

{
  endpoint: '/search',
  params: {
    from: undefined,
    q: 'keywords%3Aeleventy-plugin%20not%3Adeprecated',
    size: 250
  }
}
```

**Comment by ffflorian** [comment]
Hey @pdehaan , I'll look into this ASAP!

**Comment by ffflorian** [comment]
Thank you for the detailed report, the trick was indeed to remove `encodeURIComponent()` and just let axios manage the encoding of the search query.

**Comment by pdehaan** [comment]
Awesome, thanks!
Verified latest build works (by building a little script that [non]recursively fetches all the paged results):

```js
import { NpmsIO } from "npms.io";

const npmClient = new NpmsIO();

const plugins = await searchPackages("keywords:eleventy-plugin not:deprecated");
console.log(plugins);

async function searchPackages(query = "", size = 250) {
  const _results = [];
  let total;

  do {
    console.info(`Fetching ${size} packages (from: ${_results.length})`);
    const res = await npmClient.api.search.searchPackage(query, {
      size,
      from: _results.length,
    });
    _results.push(...res.results);
    total = res.total;
  } while (_results.length < total);
  return _results;
}
```

**Comment by ffflorian** [comment]
Great, good to see it in action!
